name: OZIP Decrypter by TechyMinati... 

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

env:
  FIRMWARE_LINK: https://otaafsg-cost.realmemobile.com/RMX1921/RMX1921EX_11.F.01_10100270_202106090048/patch/amazone2/GLO/RMX1921EX/RMX1921EX_11.F.01_10100270_202106090048/RMX1921EX_11_OTA_10100270_all_ZKZJb0lzvEYD_941be944c248.ozip #edit link here...
  FIRMWARE_NAME: RMX1921EX_11_OTA_10100270_all_ZKZJb0lzvEYD_941be944c248.ozip  #edit file name here, you can find the name of file from link itself...
  FINAL_ZIP_NAME: RMX1921EX_11_OTA_10100270_all_ZKZJb0lzvEYD_941be944c248.zip #This will be the name of final zip which will be uploaded. You can leave it unchanged.
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Downloading Ozip Now
         run: |
            sudo -E apt-get -qq update
            sudo apt install aria2
            aria2c $FIRMWARE_LINK
             
       - name: Decrypting Ozip Now
         run: |
             sudo -E apt-get -qq update
             sudo apt-get install python-pip
             sudo -H pip install --upgrade pip
             sudo -H pip install setuptools wheel docopt pycryptodome
             wget https://raw.githubusercontent.com/techyminati/oppo_ozip_decrypt/master/ozipdecrypt.py
             sudo python ozipdecrypt.py $FIRMWARE_NAME             

       - name: Upload Decrypted zip if AES keys not found.
         continue-on-error: true
         run: |
             curl https://bashupload.com/ -T *.zip #file will be uploaded to bashupload, so mirror it if you are decrypting for community uses


       - name: ziping decrypted file if needed.
         continue-on-error: true
         run: |
             cd out
             sudo zip -r $FINAL_ZIP_NAME * #Don't edit it. Don't edit it and Don't edit this line.


       - name: Upload Decrypted zip if AES keys not found.
         continue-on-error: true
         run: |
             echo "If you can't find your zip here, check the above ***UPLOAD*** section."
             cd out
             curl https://bashupload.com/ -T $FINAL_ZIP_NAME #file will be uploaded to bashupload, so mirror it if you are decrypting for community uses.
